version: '3.8'

services:
  stock-analysis:
    build: .
    container_name: stock-analysis-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount screenshots directory for debugging
      - ./screenshots:/usr/src/app/screenshots
      # Mount cookies for session persistence
      - ./screener_cookies.json:/usr/src/app/screener_cookies.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 